#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
# yabai -m config layout bsp

yabai -m config                                 \
    mouse_follows_focus          on             \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_opacity               off            \
    split_ratio                  0.5            \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  05             \
    bottom_padding               05             \
    left_padding                 05             \
    right_padding                05             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               alt            \
    mouse_action1                move           \
    mouse_drop_action            swap

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^NordVPN$" manage=off
yabai -m rule --add app="^Digital Color Meter$" manage=off
yabai -m rule --add app="^Stickies$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Mail$" manage=off
yabai -m rule --add app="^Stats$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="WhatsApp" manage=off
yabai -m rule --add app="Archive Utility" manage=off
yabai -m rule --add app="The Unarchiver" manage=off
yabai -m rule --add app="Python" manage=off
yabai -m rule --add app="mpv" manage=off

# echo "yabai configuration loaded.."
